name: Build wheels

on:
  push:
    branches:
     - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest", "macos-12"]
        python-version: ["3.10"]
        version: ["cpu", "cuda"]
        exclude:
          - os: macos-12
            version: cuda

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build wheels cpu
      uses: pypa/cibuildwheel@v2.12.2
      if: matrix.version == 'cpu'
      env:
        MACOSX_DEPLOYMENT_TARGET: 10.14
        CIBW_BEFORE_ALL_LINUX: bash build/linux_setup.sh
        CIBW_ARCHS_LINUX: x86_64
        CIBW_ARCHS_MACOS: x86_64 arm64
        CIBW_SKIP: '*-musllinux_*'
    
    - name: Build wheels cuda
      uses: pypa/cibuildwheel@v2.12.2
      if: matrix.version == 'cuda'
      env:
        CIBW_ENVIRONMENT: PATH=$PATH:/usr/local/cuda/bin
        CIBW_BEFORE_ALL_LINUX: bash build/linux_setup_cuda.sh
        CIBW_ARCHS_LINUX: x86_64
        CIBW_SKIP: '*-musllinux_*'

    - uses: actions/upload-artifact@v3
      with:
        path: ./wheelhouse/*.whl
